require 'rubygems'
require 'pathname'
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'git-up'
end

include FileUtils::Verbose

task weekly: [:'weekly:brew', :'weekly:update_evercondo', :'weekly:mas']

namespace :weekly do
  task :update_evercondo do
    paths = Pathname.glob("#{ENV['HOME']}/Projects/ruby/everapps/*")
    paths.each do |path|
      cd path do
        system 'git up'
      end
    end
  end

  task :brew do
    Bundler.with_clean_env do
      sh 'brew update'
      sh 'brew upgrade'
      sh 'brew cleanup'
    end
  end

  # run last because mas upgrade might crash
  task :mas do
    sh 'softwareupdate -l'
    sh 'mas upgrade'
  end
end

task :js do
  Dir['*.js'].each do |js|
    puts "#{js}..."
    puts File.read(js).gsub(/(\n|\t)/,'')
    puts
  end
end
